# This is an empty file, so that git commits the folder correctly

controller_manager:
  # Kontrolör yöneticisi ayarları burada belirtilir

joint_state_controller:
  # Joint durum kontrolörü ayarları burada belirtilir

camera_1_joint_position_controller:
  type: position_controllers/JointPositionController
  joint: camera_1_joint
  pid: {p: 100.0, i: 0.01, d: 10.0}